### ISSUE TITLE
Assessment Touch Ups

### ISSUE THREAD

**Issue by jmhawkins8** [devdeals/devdeals.org#3]
ASSESSMENT (Things to fix) @pjayathissa

- SK has us performing dancing in the dark (Error in code as it's SC but needs to be SK and then I think it will pull the right link as the link is right in the letters library)

No Pictures showing for:
- Sh
- Ch
- TH 
- Ng (no pic for wing) 

- Thh (how can we make this right, it needs to be th but there are two different sounds for th so it's the only way we have been able to differentiate in the code so far but makes no sense from a user perspective)

- Next button on 'ng' needs to submit (looks like link is broken otherwise)
- Make letters bigger on last page of assessment 

- Need to add sub domain for speech assessment or .co.nz

**Comment by ankit05101999** [comment]
I will check the code there is no problem

**Comment by pjayathissa** [comment]
I think there has been a misunderstanding... this issue has been posted to the wrong repository. @ankit05101999  you may close this ticket

**Comment by ankit05101999** [comment]
Okk no problem.
